# Generated by Django 4.2.5 on 2023-12-16 14:13

import BookQuestApp.book_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookQuestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=BookQuestApp.book_models.change_filename),
        ),
    ]
