# Generated by Django 4.2.5 on 2023-12-16 14:30

import BookQuestApp.book_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookQuestApp', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, default='', upload_to=BookQuestApp.book_models.change_filename),
        ),
    ]
